// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmrfvnvcvxxqqjetswyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtcmZ2bnZjdnh4cXFqZXRzd3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3ODkyNDEsImV4cCI6MjA2NzM2NTI0MX0.3UaNpKX8u7O7uukALsoxQ5XkGhzRqVVlw2XJkFXPHFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});